spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate.format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 77698982717-ojqqv1c7fggk1j1iqdkc2hmiglqhrks2.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: https://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile

  messages:
    basename: messages

springdoc:
  swagger-ui:
    oauth:
      client-id: 77698982717-ojqqv1c7fggk1j1iqdkc2hmiglqhrks2.apps.googleusercontent.com
      client-secret: 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e
      scopes:
        - openid
        - email
        - profile
    oauth2-redirect-url: https://localhost:8080/swagger-ui/oauth2-redirect.html

oauth2:
  authorizationUrl: https://localhost:8080/oauth2/authorization/google
  tokenUrl: https://www.googleapis.com/oauth2/v4/token

logging:
  pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
  file:
    path: /
    name: dpdev.log

app:
  image:
    bucket: "/Users/Denis/maven-homework/images/"

